name: "PR Auto Labeling"
description: "trigger an action based on PR description"
inputs:
  github-token:
    description: "GitHub token"
    required: true
  priority-labels:
    description: "Priority Labels in a list from highest priority to lowest"
    required: false
  classification-labels:
    description: "Classification Labels in a list from highest priority to lowest"
    required: false

outputs:
  labeled:
    description: "\"true\" if labeled otherwise \"false\""

runs:
  using: "node16"
  main: "dist/index.js"