name: "Set PR Label"
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - edited
      - opened
      - synchronize
      - reopened

jobs:
  pr-triage-manager:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: kaizen3031593/pr-triage-manager@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
